package io.nekohasekai.sagernet.fmt.trusttunnel

import android.app.Application
import androidx.sqlite.db.SupportSQLiteDatabase
import androidx.sqlite.db.SupportSQLiteOpenHelper
import androidx.sqlite.db.framework.FrameworkSQLiteOpenHelperFactory
import androidx.room.Room
import org.robolectric.RuntimeEnvironment
import io.nekohasekai.sagernet.database.ProxyEntity
import io.nekohasekai.sagernet.database.SagerDatabase
import io.nekohasekai.sagernet.fmt.KryoConverters
import io.nekohasekai.sagernet.fmt.naive.NaiveBean
import io.nekohasekai.sagernet.fmt.mieru.MieruBean
import io.nekohasekai.sagernet.fmt.hysteria.HysteriaBean
import io.nekohasekai.sagernet.ktx.parseProxies
import kotlinx.coroutines.runBlocking
import okio.ByteString.Companion.decodeBase64
import okio.ByteString.Companion.toByteString
import org.json.JSONObject
import org.junit.Assert.*
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

@RunWith(RobolectricTestRunner::class)
@Config(sdk = [28], application = Application::class, shadows = [TrustTunnelTest.NativeLogShadow::class, TrustTunnelTest.AndroidSocketReflectionShadow::class])
class TrustTunnelTest {
    // Only stub Android JNI logging; the actual protocol adapter is tested in Go.
    @org.robolectric.annotation.Implements(value = libcore.Libcore::class, isInAndroidSdk = false)
    class NativeLogShadow {
        companion object {
            @JvmStatic @org.robolectric.annotation.Implementation fun __staticInitializer__() = Unit
            @JvmStatic @org.robolectric.annotation.Implementation fun nekoLogPrintln(message: String) { android.util.Log.d("Test", message) }
        }
    }
    // JVM lacks Android's hidden Socket/FileDescriptor methods. String helpers run unchanged.
    @org.robolectric.annotation.Implements(className = "io.nekohasekai.sagernet.ktx.UtilsKt", isInAndroidSdk = false)
    class AndroidSocketReflectionShadow {
        companion object {
            @JvmStatic @org.robolectric.annotation.Implementation fun __staticInitializer__() = Unit
        }
    }
    private val human = "tt://test-user:p%40ss%3Aword@192.0.2.1:443?security=tls&hostname=cert.example.com&sni=cover.example.org&alpn=h2&client_random_prefix=12345678%2Fff00ff00#Test%20profile"
    private fun append(link: String, bytes: ByteArray): String = "tt://?" +
        (link.substring(6).decodeBase64()!!.toByteArray() + bytes).toByteString().base64Url().trimEnd('=')

    @Test fun humanFieldsAndRoundtrip() {
        val b = parseTrustTunnel(human)
        assertEquals("p@ss:word", b.password)
        assertEquals("cover.example.org", b.sni)
        assertEquals("cert.example.com", b.hostname)
        assertEquals("12345678/ff00ff00", b.clientRandomPrefix)
        assertEquals("Test profile", b.name)
        assertEquals(b.toUri(), parseTrustTunnel(b.toUri()).toUri())
        assertFalse(b.toString().contains(b.password))
    }
    @Test fun officialIndependentFixture() {
        // Hand-built TLVs, not generated by the exporter under test.
        val bytes = java.io.ByteArrayOutputStream()
        fun field(tag: Int, value: ByteArray) { bytes.write(tag); bytes.write(value.size); bytes.write(value) }
        field(0, byteArrayOf(1)); field(1, "cert.example.com".toByteArray())
        field(2, "192.0.2.1:443".toByteArray()); field(2, "[2001:db8::1]:8443".toByteArray())
        field(5, "test-user".toByteArray()); field(6, "test-password".toByteArray())
        field(4, byteArrayOf(0)); field(9, byteArrayOf(1)); field(13, byteArrayOf(7) + "1.1.1.1".toByteArray())
        val b = parseTrustTunnel("tt://?" + bytes.toByteArray().toByteString().base64Url())
        assertFalse(b.hasIpv6); assertEquals("1.1.1.1", b.dnsUpstreams)
        assertEquals(2, b.addresses.lines().size)
        assertEquals(b.toUri(), parseTrustTunnel(b.toUri()).toUri())
    }
    @Test fun unknownAndDuplicateTags() {
        val link = parseTrustTunnel(human).toUri()
        assertEquals("test-user", parseTrustTunnel(append(link, byteArrayOf(63, 2, 1, 2))).username)
        assertEquals("x", parseTrustTunnel(append(link, byteArrayOf(5, 1, 120))).username)
    }
    @Test fun malformedRejectedWithoutSecrets() {
        val link = parseTrustTunnel(human).toUri()
        for (bad in listOf("tt://?", "tt://?!!!!", append(link, byteArrayOf(0, 1, 2)),
            append(link, byteArrayOf(5, 63, 1)), append(link, byteArrayOf(4, 1, 2)),
            human.replace("12345678%2Fff00ff00", "aa%2Fffff"))) {
            assertThrows(IllegalArgumentException::class.java) { parseTrustTunnel(bad) }
        }
    }
    @Test fun unsupportedOptionsPreservedNotDowngraded() {
        val b = parseTrustTunnel(human.replace("alpn=h2", "alpn=h3"))
        assertEquals("http3", parseTrustTunnel(b.toUri()).upstreamProtocol)
        assertThrows(IllegalArgumentException::class.java) { b.buildTrustTunnelConfig(1080) }
        b.upstreamProtocol = "http2"; b.antiDpi = true
        assertThrows(IllegalArgumentException::class.java) { b.buildTrustTunnelConfig(1080) }
        b.antiDpi = false; b.dnsUpstreams = "https://dns.example.com/dns-query"
        assertThrows(IllegalArgumentException::class.java) { b.buildTrustTunnelConfig(1080) }
        b.upstreamProtocol = "unknown"
        assertThrows(IllegalArgumentException::class.java) { b.toUri() }
    }
    @Test fun mappedConfigKeepsTlsIdentity() {
        val b = parseTrustTunnel(human)
        b.finalAddress = "127.0.0.1"; b.finalPort = 23456
        b.dnsUpstreams = "1.1.1.1\ntcp://[2606:4700:4700::1111]:53"
        val j = JSONObject(b.buildTrustTunnelConfig(12345))
        assertEquals("127.0.0.1:23456", j.getString("server"))
        assertEquals("cert.example.com", j.getString("hostname"))
        assertEquals("cover.example.org", j.getString("sni"))
        assertFalse(j.getBoolean("skip_verification"))
    }
    @Test fun kryoAndEntityRegistration() {
        val b = parseTrustTunnel(human)
        val restored = KryoConverters.trustTunnelDeserialize(KryoConverters.serialize(b))!!
        assertEquals(b.toUri(), restored.toUri())
        val entity = ProxyEntity(); entity.putBean(b)
        assertEquals(ProxyEntity.TYPE_TRUSTTUNNEL, entity.type)
        assertTrue(entity.needExternal()); assertEquals("TrustTunnel", entity.displayType())
        assertEquals(b.toUri(), entity.toStdLink())
    }
    @Test fun mixedSubscriptionPreservesExistingProtocols() = runBlocking {
        val proxies = parseProxies(listOf(human, parseTrustTunnel(human).toUri(),
            "naive+https://test-user:test-password@naive.example.com:443#Naive",
            "mierus://test-user:test-password@mieru.example.com?port=2012&protocol=TCP#Mieru",
            "hysteria2://test-password@hy.example.com:443?sni=hy.example.com#Hy2").joinToString("\n"))
        assertEquals(proxies.map { it.javaClass.simpleName }.toString(), 5, proxies.size)
        assertEquals(2, proxies.filterIsInstance<TrustTunnelBean>().size)
        assertEquals(1, proxies.filterIsInstance<NaiveBean>().size)
        assertEquals(1, proxies.filterIsInstance<MieruBean>().size)
        assertEquals(1, proxies.filterIsInstance<HysteriaBean>().size)
    }
    @Test fun hy2AliasesPreserveTlsPortAndEncodedPassword() = runBlocking {
        for (scheme in listOf("hysteria2", "hy2")) {
            val parsed = parseProxies("$scheme://fixture%3Apassword%40only@hy.example.com:8443?sni=cert.example.com&insecure=0#Hysteria")
            val b = parsed.single() as HysteriaBean
            assertEquals(2, b.protocolVersion.toInt())
            assertEquals("8443", b.serverPorts)
            assertEquals("fixture:password@only", b.authPayload)
            assertEquals("hy.example.com", b.serverAddress)
            assertEquals("cert.example.com", b.sni)
            assertFalse(b.allowInsecure)
            assertTrue(b.obfuscation.isEmpty())
            assertEquals(b.authPayload, (KryoConverters.hysteriaDeserialize(KryoConverters.serialize(b))!!).authPayload)
        }
    }
    @Test fun importLogsNeverContainLinksOrParserExceptionSecrets() = runBlocking {
        org.robolectric.shadows.ShadowLog.clear()
        val secret = "PRIVATE-CREDENTIAL-FIXTURE"
        val links = listOf(
            "hysteria2://$secret@hy.example.com:443?sni=hy.example.com",
            "hy2://$secret@hy.example.com:99999",
            "naive+https://user:$secret@naive.example.com:443",
            "mierus://user:$secret@mieru.example.com?port=2012",
            "vless://$secret@x.example.com:99999?type=xhttp",
            "tt://user:$secret@tt.example.com:443?alpn=h2")
        parseProxies(links.joinToString("\n"))
        val logs = org.robolectric.shadows.ShadowLog.getLogsForTag("Test").joinToString("\n") { it.msg }
        assertTrue(logs.isNotEmpty())
        assertFalse(logs.contains(secret))
        assertFalse(logs.contains("hy.example.com"))
        assertFalse(logs.contains("naive.example.com"))
        assertFalse(logs.contains("vless://"))
    }
    @Test fun networkFailureCategoriesDoNotIncludePrivateErrorText() {
        fun category(text: String) = io.nekohasekai.sagernet.ktx.connectionFailureCategory(java.io.IOException(text))
        assertEquals("QUIC_NO_RESPONSE", category("timeout: no recent network activity; private.example"))
        assertEquals("CANCELLED", category("dial udp private.example: operation was canceled"))
        assertEquals("TLS_CERTIFICATE", category("x509: certificate is invalid for private.example"))
        assertEquals("CONNECTION_FAILED", category("private-password-value"))
    }
    @Test fun dedupKeepsDistinctAccounts() {
        val first = parseTrustTunnel(human)
        val second = first.clone().apply { password = "another-password" }
        val renamed = first.clone().apply { name = "Renamed" }
        fun key(b: TrustTunnelBean) = moe.matsuri.nb4a.Protocols.Deduplication(b, "trusttunnel")
        assertNotEquals(key(first), key(second))
        assertEquals(key(first), key(renamed))
    }
    @Test fun plainAndBase64SubscriptionEntryPoint() = runBlocking {
        val raw = human + "\n" + parseTrustTunnel(human).toUri()
        for (text in listOf(raw, raw.toByteArray().toByteString().base64())) {
            val parsed = io.nekohasekai.sagernet.group.RawUpdater.parseRaw(text)!!
            assertEquals(2, parsed.size)
            assertTrue(parsed.all { it is TrustTunnelBean })
        }
    }
    @Test fun migrationPreservesExistingProfiles() {
        val context = RuntimeEnvironment.getApplication()
        val name = "migration-test.db"
        context.deleteDatabase(name)
        val schema = javaClass.classLoader!!.getResourceAsStream("io.nekohasekai.sagernet.database.SagerDatabase/8.json")!!.bufferedReader().use { JSONObject(it.readText()).getJSONObject("database") }
        val helper = FrameworkSQLiteOpenHelperFactory().create(SupportSQLiteOpenHelper.Configuration.builder(context)
            .name(name).callback(object : SupportSQLiteOpenHelper.Callback(7) {
                override fun onCreate(db: SupportSQLiteDatabase) {
                    val entities = schema.getJSONArray("entities")
                    for (i in 0 until entities.length()) {
                        val table = entities.getJSONObject(i)
                        db.execSQL(table.getString("createSql").replace("\${TABLE_NAME}", table.getString("tableName")).replace(", `trustTunnelBean` BLOB", ""))
                        val indices = table.getJSONArray("indices")
                        for (j in 0 until indices.length()) db.execSQL(indices.getJSONObject(j).getString("createSql").replace("\${TABLE_NAME}", table.getString("tableName")))
                    }
                }
                override fun onUpgrade(db: SupportSQLiteDatabase, oldVersion: Int, newVersion: Int) = Unit
            }).build())
        helper.writableDatabase.execSQL("INSERT INTO proxy_entities (id,groupId,type,userOrder,tx,rx,status,ping,uuid,xhttpBean) VALUES (7,1,23,0,1,2,0,55,'existing',X'010203')")
        helper.close()
        // Room validates every table against the generated schema after migration.
        val migrated = Room.databaseBuilder(context, SagerDatabase::class.java, name)
            .addMigrations(SagerDatabase.MIGRATION_7_8).allowMainThreadQueries().build()
        try {
            migrated.openHelper.writableDatabase.query("SELECT uuid,xhttpBean,trustTunnelBean,tx,rx FROM proxy_entities WHERE id=7").use {
                assertTrue(it.moveToFirst()); assertEquals("existing", it.getString(0))
                assertArrayEquals(byteArrayOf(1, 2, 3), it.getBlob(1)); assertTrue(it.isNull(2))
                assertEquals(1, it.getInt(3)); assertEquals(2, it.getInt(4))
            }
        } finally { migrated.close(); context.deleteDatabase(name) }
    }
}
